enum DELIVERY_TYPE {
    EXPRESS = 'EXPRESS',
    ECONOMY = 'ECONOMY'
}

enum VEHICLE_TYPES {
    MOTORBIKE = 'MOTORBIKE',
    VAN = 'VAN',
    PICKUP_TRUCK = 'PICKUP_TRUCK',
    TRUCK = 'TRUCK',
}

enum PACKAGE_TYPES {
    DOCUMENT = 'DOCUMENT',
    ELECTRONICS = 'ELECTRONICS',
    FOOD = 'FOOD',
    CLOTHING = 'CLOTHING',
    FRAGILE = 'FRAGILE',
    OTHERS = 'OTHERS'
}

enum ORDER_TYPES {
    MOTORBIKE_DELIVERY = 'MOTORBIKE_DELIVERY',
    CAR_DELIVERY = 'CAR_DELIVERY',
}

enum GENDER {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHERS = 'OTHERS'
}

enum ROLE {
    CUSTOMER = 'CUSTOMER',
    DRIVER = 'DRIVER',
    ADMIN = 'ADMIN',
    SYSADMIN = 'SYSADMIN'
}

export {
    DELIVERY_TYPE, VEHICLE_TYPES,
    PACKAGE_TYPES, ORDER_TYPES,
    GENDER, ROLE
}