enum DELIVERY_TYPE {
    EXPRESS = 'EXPRESS',
    ECONOMY = 'ECONOMY'
}

enum VEHICLE_TYPES {
    MOTORBIKE = 'MOTORBIKE',
    VAN = 'VAN',
    PICKUP_TRUCK = 'PICKUP_TRUCK',
    TRUCK = 'TRUCK',
}

enum PACKAGE_TYPES {
    DOCUMENT = 'DOCUMENT',
    ELECTRONICS = 'ELECTRONICS',
    FOOD = 'FOOD',
    CLOTHING = 'CLOTHING',
    FRAGILE = 'FRAGILE',
    OTHERS = 'OTHERS'
}

enum ORDER_TYPES {
    MOTORBIKE_DELIVERY = 'MOTORBIKE_DELIVERY',
    CAR_DELIVERY = 'CAR_DELIVERY',
}

enum GENDER {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHERS = 'OTHERS'
}

enum ROLE {
    CUSTOMER = 'CUSTOMER',
    DRIVER = 'DRIVER',
    ADMIN = 'ADMIN',
    SYSADMIN = 'SYSADMIN'
}

enum LOCATION_TYPE {
    PICKUP = 'PICKUP',
    DROP_OFF = 'DROP_OFF',
}

enum DELIVERY_STATUS {
    PENDING = 'PENDING',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}

enum DRIVER_STATUS {
    AVAILABLE = 'AVAILABLE',
    BUSY = 'BUSY',
    OFFLINE = 'OFFLINE',
}

export {
    DELIVERY_TYPE, VEHICLE_TYPES,
    PACKAGE_TYPES, ORDER_TYPES, DRIVER_STATUS,
    GENDER, ROLE, LOCATION_TYPE, DELIVERY_STATUS
}